CREATE DATABASE IF NOT EXISTS securevote;
USE securevote;

CREATE TABLE IF NOT EXISTS candidates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  office VARCHAR(120) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE / AUTHORIZED',
  votes INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS votes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  voter_id VARCHAR(100) NOT NULL,
  candidate_id INT NOT NULL,
  voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_vote_per_voter (voter_id),
  FOREIGN KEY (candidate_id) REFERENCES candidates(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB;
